AllCops:
  TargetRubyVersion: 2.5
  NewCops: enable

Layout/LineLength:
  Max: 100

Metrics/AbcSize:
  Max: 20
  Exclude:
    - spec/db_helper.rb

Metrics/BlockLength:
  IgnoredMethods:
    - let
    - it
    - describe
    - context
    - specify
    - define
  Exclude:
    - spec/dbee/**/*
    - dbee-active_record.gemspec

Metrics/ClassLength:
  Max: 150

Metrics/MethodLength:
  Max: 25
  Exclude:
    - spec/db_helper.rb
